openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the Retrieval-Augmented Generation chatbot functionality using Google Gemini
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local development server
paths:
  /chat/query:
    post:
      summary: Query the RAG chatbot
      description: Send a query to the chatbot and receive a response based on book content using Google Gemini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - chapter_id
              properties:
                query:
                  type: string
                  description: The user's question/query
                  example: "What is embodied intelligence?"
                chapter_id:
                  type: string
                  description: The chapter ID to focus the search on
                  example: "ch001-intro-physical-ai"
                user_id:
                  type: string
                  description: Optional user ID for personalized responses
                  example: "user-123-abc"
                selected_text:
                  type: string
                  description: Optional selected text to constrain the response
                  example: "Embodied intelligence refers to AI systems that interact with the physical world..."
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                  - sources
                  - query_id
                properties:
                  response:
                    type: string
                    description: The chatbot's response to the query
                    example: "Embodied intelligence refers to AI systems that interact with the physical world..."
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        chapter_id:
                          type: string
                          example: "ch001-intro-physical-ai"
                        chapter_title:
                          type: string
                          example: "Introduction to Physical AI"
                        section:
                          type: string
                          example: "Embodied Intelligence Definition"
                        page_reference:
                          type: string
                          example: "p. 15"
                  query_id:
                    type: string
                    description: Unique identifier for the query
                    example: "query-456-def"
        '400':
          description: Bad request - missing required fields
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error
  /chat/history:
    get:
      summary: Get chat history
      description: Retrieve the chat history for a specific user
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
          description: The user ID to retrieve history for
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Number of recent conversations to return
      responses:
        '200':
          description: Chat history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        query_id:
                          type: string
                          example: "query-456-def"
                        query:
                          type: string
                          example: "What is embodied intelligence?"
                        response:
                          type: string
                          example: "Embodied intelligence refers to AI systems that interact with the physical world..."
                        timestamp:
                          type: string
                          format: date-time
                          example: "2023-10-20T10:30:00Z"
        '400':
          description: Bad request - missing user_id
        '500':
          description: Internal server error