openapi: 3.0.0
info:
  title: Translation API
  description: API for translating book content to Urdu using Google Gemini
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local development server
paths:
  /translate/urdu:
    post:
      summary: Translate chapter to Urdu
      description: Translate a chapter to Urdu while preserving technical accuracy using Google Gemini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapter_id
                - user_id
              properties:
                chapter_id:
                  type: string
                  description: The chapter ID to translate
                  example: "ch001-intro-physical-ai"
                user_id:
                  type: string
                  description: The user ID requesting translation (must be logged in)
                  example: "user-123-abc"
                preserve_formatting:
                  type: boolean
                  description: Whether to preserve original formatting
                  default: true
                preserve_code_blocks:
                  type: boolean
                  description: Whether to preserve code blocks unchanged
                  default: true
      responses:
        '200':
          description: Translation completed successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - urdu_content
                  - translation_id
                properties:
                  urdu_content:
                    type: string
                    description: The translated chapter content in Urdu
                    example: "۔۔۔ جسمانی مصنوعی ذہانت کا تعارف\n\nجسمانی مصنوعی ذہانت وہ ہے جہاں..."
                  translation_id:
                    type: string
                    description: Unique identifier for the translation
                    example: "trans-789-ghi"
                  original_hash:
                    type: string
                    description: Hash of original content for cache validation
                    example: "a1b2c3d4e5f6"
                  processing_time:
                    type: number
                    description: Time taken to process the translation in seconds
                    example: 4.2
        '400':
          description: Bad request - missing required fields or user not authenticated
        '401':
          description: Unauthorized - user not logged in
        '404':
          description: Chapter not found
        '429':
          description: Rate limit exceeded for translations
        '500':
          description: Internal server error
  /translate/cache/validate:
    post:
      summary: Validate translation cache
      description: Check if cached translation is still valid based on content hash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapter_id
                - user_id
                - original_hash
              properties:
                chapter_id:
                  type: string
                  description: The chapter ID
                  example: "ch001-intro-physical-ai"
                user_id:
                  type: string
                  description: The user ID
                  example: "user-123-abc"
                original_hash:
                  type: string
                  description: Hash of the original content to validate against
                  example: "a1b2c3d4e5f6"
      responses:
        '200':
          description: Cache validation result
          content:
            application/json:
              schema:
                type: object
                required:
                  - is_valid
                properties:
                  is_valid:
                    type: boolean
                    description: Whether the cached translation is still valid
                    example: true
                  cached_content:
                    type: string
                    description: Cached content if valid
                    example: "۔۔۔ جسمانی مصنوعی ذہانت کا تعارف\n\nجسمانی مصنوعی ذہانت وہ ہے جہاں..."
        '400':
          description: Bad request - missing required fields
        '404':
          description: No cached translation found
        '500':
          description: Internal server error
  /translate/switch:
    post:
      summary: Switch content language
      description: Toggle between original and translated content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapter_id
                - user_id
                - target_language
              properties:
                chapter_id:
                  type: string
                  description: The chapter ID
                  example: "ch001-intro-physical-ai"
                user_id:
                  type: string
                  description: The user ID
                  example: "user-123-abc"
                target_language:
                  type: string
                  description: Target language ('original' or 'urdu')
                  enum: [original, urdu]
                  example: "urdu"
      responses:
        '200':
          description: Content language switched successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - content
                  - language
                properties:
                  content:
                    type: string
                    description: The content in requested language
                    example: "۔۔۔ جسمانی مصنوعی ذہانت کا تعارف\n\nجسمانی مصنوعی ذہانت وہ ہے جہاں..."
                  language:
                    type: string
                    description: The language of the returned content
                    example: "urdu"
        '400':
          description: Bad request - invalid language or missing fields
        '404':
          description: Chapter or translation not found
        '500':
          description: Internal server error